"""Handle RAG queries — call the remote LLM and upload output files."""

from pathlib import Path


class RagHandler:
    """Query the RAG agent and upload any output files back to Slack."""

    def __init__(self, rag, vol):
        self._rag = rag
        self._vol = vol

    def handle(self, message: str, thread_ts: str, channel: str, say, client) -> None:
        text, output_files = self._rag.query.remote(message)
        say(text)
        if output_files:
            self._upload_files(output_files, channel, thread_ts, client)

    def _upload_files(self, output_files: list[str], channel: str, thread_ts: str, client) -> None:
        """Upload files generated by execute_python (charts, CSVs, etc.) to the thread."""
        self._vol.reload()
        for p in [Path(f) for f in output_files]:
            if p.exists():
                client.files_upload_v2(
                    channel=channel, thread_ts=thread_ts,
                    file=str(p), filename=p.name, title=p.name,
                )
